### ISSUE TITLE
TypeError: this.currencyWithLedgerPairs[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-connector-backend-yahoo#1]
Having issue with it.  
```
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector] 2016-12-15T10:34:49.402Z connector:app error TypeError: this.currencyWithLedgerPairs[Symbol.iterator] is not a function
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at YahooFinanceBackend.getQuote (/home/winthan/ilp-kit/node_modules/ilp-connector-backend-yahoo/index.js:88:24)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at RouteBroadcaster.<anonymous> (/home/winthan/ilp-kit/node_modules/ilp-connector/src/lib/route-broadcaster.js:164:40)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at next (native)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at onFulfilled (/home/winthan/ilp-kit/node_modules/co/index.js:65:19)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at /home/winthan/ilp-kit/node_modules/co/index.js:54:5
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at co (/home/winthan/ilp-kit/node_modules/co/index.js:50:10)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at RouteBroadcaster._tradingPairToLocalRoute (/home/winthan/ilp-kit/node_modules/ilp-connector/src/lib/route-broadcaster.js:163:12)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at Promise.all.tradingPairs.toArray.map (/home/winthan/ilp-kit/node_modules/ilp-connector/src/lib/route-broadcaster.js:132:22)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at Array.map (native)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at RouteBroadcaster._getLocalRoutes (/home/winthan/ilp-kit/node_modules/ilp-connector/src/lib/route-broadcaster.js:131:52)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at RouteBroadcaster.reloadLocalRoutes (/home/winthan/ilp-kit/node_modules/ilp-connector/src/lib/route-broadcaster.js:126:36)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at next (native)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at onFulfilled (/home/winthan/ilp-kit/node_modules/co/index.js:65:19)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at /home/winthan/ilp-kit/node_modules/co/index.js:54:5
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at co (/home/winthan/ilp-kit/node_modules/co/index.js:50:10)
Dec 15 10:34:49 newyork ilp-kit[7888]: [connector]     at toPromise (/home/winthan/ilp-kit/node_modules/co/index.js:118:63)   
```

**Comment by emschwartz** [comment]
I ran into this issue too and pushed a fix for it. Try re-installing the module.

Sorry about that, I did it super quickly and without tests.

**Comment by Winthan** [comment]
@emschwartz 👍 . It works , thanks for the module.

**Comment by Winthan** [comment]
this is resloved.
